# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all

College.destroy_all

Favorite.destroy_all

#USER

User.create(first_name:"Aicha",last_name:"Diallo", email:"adiallo@hotmail.com", password:"12345" )

# 20.times do 
#     User.create(
#         first_name: Faker::Name.first_name,
#         last_name: Faker::Name.last_name,
#         email: Faker::Internet.free_email,
#         password: Faker::Internet.password
#     )
# end

#Colleges

 c1= College.create(image:"https://media2.trover.com/T/54c8f96326c48d7384000b5d/fixedw.jpg", name:"Harvard College", location:"Cambridge, MA", tuition:"$50,420", overview:"Harvard, founded in 1636, is a private, Ivy League institution. Its undergraduate college has no established freshman program. Students sample courses at the beginning of each semester and create their own study plan with an academic advisor. At the undergraduate level, Harvard promotes close collaboration between students and faculty on coursework and research. Its popular Freshman Seminar Program enables small groups of first-year students to work intimately with faculty on any of 130 different topics. Nearly all Harvard undergraduates live on campus for the first year in dormitories and later in Houses led by senior faculty members. Harvard's historic 380-acre campus is located in Cambridge, across the Charles River from Boston", website: "www.harvard.edu/")

c2= College.create(image:"https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_768,q_50,w_1024/v1/clients/princetonnj/princeton_university_main_building_at_front_gate_geraldine_scull_209cbd93-c4fc-4485-a274-66b4076c71e0.jpg", name:"Princeton University", location:"Princeton, NJ", tuition:"$50,340", overview:"Princeton, founded in 1746, is a private, Ivy League, comprehensive university. Its 600-acre campus is located in a residential section of Princeton, 50 miles southwest of New York City. The main campus includes Georgian and Gothic architectural styles and contemporary structures by I.M. Pei and Robert Venturi.", website: "www.princeton.edu/")

c3= College.create(image:"https://d28htnjz2elwuj.cloudfront.net/wp-content/uploads/2013/01/amherst-college-feat.jpg", name:"Amherst College", location:"Amherst, MA", tuition:"$56,426", overview:"Amherst College is one of the nation's premier private, national liberal arts and sciences colleges. The student body of 1,650 includes students from 50 states and 30 countries - 30% are students of color, 46% receive need-based aid, and 5% are non-U.S. citizens. Two distinctive features of an Amherst education are its open curriculum (no core or distribution requirements) and its membership in a five-college consortium of nearby schools (providing students with the resources of a much larger institution). Founded in 1821 as an educational institution for men, it began admitting women in 1975. Its 978-acre campus is located close to the center of Amherst, 55 miles west of Worcester, Massachusetts, 90 minutes west of Boston and three hours north of New York City.", website: "www.amherst.edu/")

c4= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQbMLHKLqLi77oB8b0ak6e1tcyOMqG8PNqHgUb94SN8qwl5WkIj", name:"Mount Holyoke College", location:"South Hadley, MA", tuition:"$49,998", overview:"Mount Holyoke College, founded in 1837, is a private, liberal arts college for women. It is a top-ranked, highly selective, private liberal arts college enrolling 2,000 remarkable women from across the U.S. and around the world. With its highly-charged learning environment, Mount Holyoke offers 44 majors, small classes, and a 10:1 student/faculty ratio. A leader in higher education for women, Mount Holyoke has always encouraged purposeful engagement with the world. The college's emphases include connected learning, leadership, technological and environmental literacy and excellence in speaking, arguing and writing. Distinguished by the beauty of its campus, Mount Holyoke is a member of the prestigious Five College Consortium which offers 5,000+ courses to 30,000 undergraduates in the Pioneer Valley of western Massachusetts, one of the nation's most culturally vibrant regions. Its 800-acre campus, including numerous 19th-century buildings, is located in South Hadley, 10 miles north of Springfield.", website: "www.mtholyoke.edu/")

c5= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR7wkHHhvmYtCv9xyXKfK5anPCfLC_75C59qSMBFckEm4xbER4A", name:"George Mason University", location:"Fairfax, VA", tuition:"$12,462 (in-state)", overview:"George Mason, founded in 1972, is a public university. Programs are offered through the Colleges of Arts and Sciences and Nursing and Health Science; the Schools of Information Technology and Engineering and Management; the Institutes of the Arts and Public Policy; the New Century College; the Institutes for Conflict Analysis and Resolution, Biosciences, Bioinformatics, and Biotechnology; and the Graduate School of Education. Its 677-acre main campus is located in Fairfax, 18 miles from Washington, DC.", website: "www.gmu.edu/")

c6= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTv9NZRR2c6ZmWoI6jh1pvr6ilcX84n6mrqtxu5ZH1qQxx0G3Jb", name:"Stanford University", location:"Stanford, CA", tuition:"$51,354", overview:"Stanford University, founded in 1891, is a private, comprehensive, research-intensive university, where teaching, learning and research are part of a single enterprise. Stanford's enterprising character draws from its Western location and from the legacy of Jane and Leland Stanford. Its areas of excellence range from the humanities to the social sciences, engineering and the sciences. The layout and character of Stanford's Quadrangle were developed by Frederick Olmsted, designer of New York's Central Park. The 8,180-acre campus includes Moorish Spanish and French Romanesque architecture. It is located in Stanford, adjacent to Palo Alto, 30 miles south of San Francisco.", website: "www.stanford.edu/")

c7= College.create(image:" https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPuD3SnQWSwew9EL25AmipUMJ28lhdVEdgd6zubSII1CW2kxRi", name:"Howard University", location:"Washington, DC", tuition:"$26,756", overview:"Howard University, founded in 1867, is a private, comprehensive, historically black university. Programs are offered through the Colleges of Arts and Sciences; Dentistry; Engineering, Architecture and Computer Sciences; Medicine; and Pharmacy, Nursing and Allied Health Sciences; through the Schools of Business, Communications, Divinity, Education, Law and Social Work; and through the Graduate School of Arts and Sciences. Howard has an international faculty representing over 65 countries and a student body from 104 countries. This makes for personal growth and academic excellence. The university has the largest collection of materials dealing with people of color of any university in the world. It also has available close by the resources of many important government agencies and the Congress of the United States. Its main campus is located in central Washington, DC.", website: "www.howard.edu/")

c8= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQwQqwFRbrz1JeXUbbsbbvVTGr7kZ68qjmpXe-KEcj_jDYT-G2p", name:"University of Southern California", location:"Los Angeles, CA", tuition:"$54,323", overview:"The University of Southern California, founded in 1880, is a private, comprehensive university. As a major research university, USC provides undergraduates with an extraordinary range of academic programs and encourages study and research across disciplines. This breadth of programs means that students can combine both strong liberal arts and professional studies. USC's 155-acre main campus location puts the incomparable resources offered by Los Angeles and southern California within easy reach. Students draw on these resources for research and internships, for exploring arts and community service and for working at the center of developing information technologies. Within this driven, forward-thinking, far-flung area, USC students maintain a strong sense of community.", website:"www.usc.edu/")

c9= College.create(image:" https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT8TpXKfDzs2NpEVSA5Kjzbiq0bQJOAjdlpXl8YQWLGH6_9EhGw", name:"Hampton University", location:"Hampton, VA", tuition:"$25,442", overview:"Hampton University, founded in 1868, is an historically black, private liberal arts university, dedicated to the promotion of learning, the building of character and the preparation of promising students for positions of leadership and service. Its curriculum emphasizes science, business and liberal arts. Programs are offered through the Schools of Business, Engineering and Technology, Liberal Arts and Education, Nursing, Pharmacy, and Science, and through the College of Continuing Education and the Graduate College. Hampton University serves students from diverse national, cultural and economic backgrounds.", website:"www.hamptonu.edu/")


c10= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQN0Xt57oqjBKVf-jF-ExYsHOMjsEO8IacZ3LS2c5hKxrNxnlaH", name:"Wellesley College", location:"Wellesley, MA", tuition:"$53,732", overview:"Wellesley College, founded in 1870, is a private, liberal arts college for women. Its 500-acre campus and arboretum is located in Wellesley, 12 miles west of Boston. It is committed to intellectual scholarship, research and innovative teaching in a context in which women can achieve and flourish. The college has a comprehensive curriculum, a top-notch, accessible faculty and a strong support network on campus as well as a very active and impressive alumnae network. Campus buildings encompass a variety of architectural styles ranging from Gothic to contemporary.", website:"www.wellesley.edu/")


c11= College.create(image:" https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSN4gMeC83niLDxFLnSwG30MENAk7lTncUXUh1k6O8LeEyHrRNS", name:"Johns Hopkins University", location:"Baltimore, MD", tuition:"$53,740", overview:"Johns Hopkins University, founded in 1876, is a private university. It is one of the smallest national research universities in terms of enrollment, giving undergraduates, including freshmen, access to equipment, resources, internships, research positions and the internationally recognized faculty. The school is committed to helping create new student organizations and activities. Undergraduate education is enhanced by the student's ability to take courses in other divisions of the university, including the Schools of Public Health, Medicine, Nursing, and International Studies, and the Peabody Conservatory of Music. Its 140-acre campus is located in a residential area of northern Baltimore.", website: "www.jhu.edu/")


c12= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQB60uLl104sFakTPqUASjaPqEc-sY_V2GoV0ys36zFhe0PTfR3", name:"Wesleyan University", location:"Middletown, CT",tuition:"$57,004", overview:"Wesleyan University is a small, private, liberal arts university, founded in 1831. Intellectual independence, critical thinking skills, and the ability to see the connection between distinct fields of learning are the goals of a Wesleyan education. Students are encouraged to see themselves as scholars, to participate in the exchange of ideas, and to form close working relationships with professors. Wesleyan describes its environment as academically demanding but noncompetitive: one that allows students to find their niche in the classroom, in campus life, and in the wider community. Wesleyan's 240-acre campus is located 15 miles south of Hartford.", website: "www.wesleyan.edu/")


c13= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ2FWwUS2G7sfIl8ERifJiiOk1BzP2kyW83Xa_LHchJcY5sXf79", name:"Northwestern University", location:"Evanston, IL", tuition:"$54,567", overview:"Northwestern University, founded in 1851, is a private, comprehensive university. It offers unusual flexibility combined with a wide choice of academic concentrations. Programs are offered through the Weinberg College of Arts and Sciences; the Schools of Education and Social Policy, Law, Music, and Speech; the Graduate School; the Kellogg Graduate School of Management; the McCormick School of Engineering and Applied Science; the Medical School; and the Medill School of Journalism. In addition to over 70 established majors, students can choose or design nontraditional combinations. In addition, a broad range of field experiences, internships and programs combining work and study are part of the academic program of a large percentage of the students. Because Chicago is only 30 minutes away, students have the cultural advantage of the music, theatre, museums, sports and entertainment of a world-class city to enrich their undergraduate experience. Its 250-acre campus is located in Evanston, 12 miles north of Chicago.", website: "www.northwestern.edu/")


c14= College.create(image:"https://steinhardt.nyu.edu/sites/default/files/styles/page_hero/public/2019-08/nyc_school_buildings_18-0062_NYU_232%20%281%29.jpg?h=e5aec6c8&itok=7TQ-mQaF ", name:"New York University", location:"New York, NY", tuition:"$51,828", overview:"New York University, founded in 1831, is a private, comprehensive institution. Offering more than 2,500 courses, the undergraduate program aims to cultivate inquiry, creativity, and independent ambition in all students, and to challenge them intellectually, professionally, and personally. The main campus, located in Greenwich Village in Manhattan, has no walls or gates to maintain a connection to the surrounding city. Fourteen smaller schools within the university maintain their own traditions, programs, and faculty. NYU also has branch campuses in 10 countries on four continents, including Abu Dhabi, UAE.", website: "www.nyu.edu/")


c15= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTrJJ27fMZUm8qIpXXfvpTJ11uzT7Cl2xlWNyy7hSxk4-Zc03L3", name:"Dartmouth College", location:"Hanover, NH", tuition:"$57,204", overview:"Dartmouth, founded in 1769, is a private, Ivy League college. Dartmouth's 265-acre campus is located in Hanover, northwest of Boston. Dartmouth is committed to promoting and celebrating the diversity of its community members. ", website: "www.dartmouth.edu/")


c16= College.create(image:"https://res.cloudinary.com/highereducation/image/upload/w_740,h_416,c_fill,f_auto,fl_lossy,q_auto/v1/TheBestSchools.org/texas-tech-university.jpg", name:"Texas Tech University", location:"Lubbock, TX", tuition:"$26,437", overview:"Texas Tech University, founded in 1923, is a public, comprehensive university. It is the largest university in the western two-thirds of Texas. The single-campus arrangement of the university, with a law school and health sciences center, is unique in the state, allowing easy transition to law and advanced degrees as well as professional degrees in health care fields. Programs are offered through the Colleges of Agricultural Sciences and Natural Resources, Architecture, Arts and Sciences, Business Administration, Education, Engineering, and Human Sciences. ", website: "www.ttu.edu/")


c17= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR-hmA4nvnf2JXynDn8pw-IIIYcsfIGec4eKFPgMhfNY1dQlXIa", name:"University of Nebraska", location:"Lincoln, NE", tuition:"$24,912", overview:"The University of Nebraska - Lincoln, founded in 1869, is a public institution offering students numerous academic and social options. Within various learning communities, faculty, staff, and students share academic interests, study for exams, and discuss ideas. UNL's 623-acre campus is located in Lincoln, 55 miles southwest of Omaha.", website: "www.unl.edu/")


c18= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmKTxclvWNu-Dgh1XSenTe2ejn13TUKVyWUUJDDpcztsnkVmqs", name:"University of Tennessee", location:"Knoxville, TN", tuition:"31,510", overview:"The University of Tennessee, Knoxville is a public, comprehensive university. Founded as a private college in 1794, it became the first campus of the University of Tennessee in 1879. UTK graduates finish college with less debt than students at most national universities.Programs are offered through the Colleges of Agricultural Sciences and Natural Resources, Architecture and Design, Arts and Sciences, Business Administration, Communications, Education, Engineering, Human Ecology, Law, Nursing, Social Work, and Veterinary Medicine, and the Schools of Biomedical Sciences and Information Sciences. Many programs are ranked among the best in the nation, including accountancy, business and law.", website: "www.utk.edu/")


c19= College.create(image:"https://www.thoughtco.com/thmb/hBrJs3spr1U01iYNrn9WMK8McBA=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1144644106-25fc348fa156462eb515eb37236f8896.jpg", name:"Loyola Marymount University", location:"Los Angeles, CA", tuition:"$48,172", overview:"Loyola Marymount University is committed to the encouragement of learning, the education of the whole person, the service of faith, and the promotion of justice and interculturalism. Its 128-acre campus is located in a residential area of Los Angeles.", website: "www.lmu.edu/")


c20= College.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQzW0N89l4Nl8kzDY72QO13AvmOxmbZLIyXN8TDvj2kwwskZbqc", name:"Georgetown University", location:"Washington, DC", tuition:"$54,104", overview:"Georgetown University, founded in 1789, provides a traditional liberal arts education with a strong international influence. Its location facilitates exchanges with the national government and international agencies for both students and faculty. Many internship opportunities are available on Capitol Hill and with the many nonprofit organizations located in the nation's capital. Programs are offered through Georgetown College and the Schools of Business Administration, Foreign Service and Nursing. Its 110-acre campus is located in Washington, DC. The oldest campus building dates from 1795 and is in the Flemish Renaissance style.", website: " www.georgetown.edu/")


#Favorites

f1= Favorite.create(user_id:1, image:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQzW0N89l4Nl8kzDY72QO13AvmOxmbZLIyXN8TDvj2kwwskZbqc", name:"Georgetown University", location:"Washington, DC", tuition:"$54,104", overview:"Georgetown University, founded in 1789, provides a traditional liberal arts education with a strong international influence. Its location facilitates exchanges with the national government and international agencies for both students and faculty. Many internship opportunities are available on Capitol Hill and with the many nonprofit organizations located in the nation's capital. Programs are offered through Georgetown College and the Schools of Business Administration, Foreign Service and Nursing. Its 110-acre campus is located in Washington, DC. The oldest campus building dates from 1795 and is in the Flemish Renaissance style.", website: " www.georgetown.edu/")
